### ISSUE TITLE
App crashes when not using English

### ISSUE THREAD

**Issue by Halibutt** [nicolas-raoul/apps-android-commons#41]
The app installs fine, I can log in, first sync starts. The file counter stops at 500 and doesn't proceed any further than that (I uploaded almost 1500 I believe) and the info on top says "Waiting for first synchronisation" (translated from Polish, not sure what the English text says). 

I can then proceed to take a photo, fill in the title and description (the text below reads "The image will be shared under CCu00A0Uznanie autorstwa-Na tych samych warunkachu00A03.0" - clearly it should be "CC-Uznanie autorstwa-Na tych samych warunkach", or something along those lines; all the license available in settings have wrong names as well). But when I click proceed, an error "Wystąpił błąd Commons." ("A Commons error happened") appears, with an option to send an email. Same thing happens when I try to upload a picture from the ones I took before. 

All in all, the app as it is now is unusable right now. I'd be happy to help though, just let me know how.

**Comment by nicolas-raoul** [comment]
Hi Halibutt,

Thanks for your feedback!

1. What version of Android are you using?
2. Does that also happen with the latest version? (1.6 released today)

**Comment by Halibutt** [comment]
Hi, following your comment at Play Store I redownloaded the app today, so yes, it's 1.6.

The abbreviations and numbers for my phone:
Model: ALE-L21
Android: 5.0
EMUI 3.1

I guess the problem might be with the fact that Huawei P8's come preinstalled with EMUI add-on, but it's a wild guess.

**Comment by nicolas-raoul** [comment]
I think I understand where the bug is :-)

**Comment by Halibutt** [comment]
Cool! Curiosity is killing me. Is it fixable?

**Comment by nicolas-raoul** [comment]
```
java.util.UnknownFormatConversionException: Conversion: 1$
at java.util.Formatter$FormatSpecifierParser.unknownFormatConversionException(Formatter.java:2321)
at java.util.Formatter$FormatSpecifierParser.advance(Formatter.java:2315)
at java.util.Formatter$FormatSpecifierParser.parseConversionType(Formatter.java:2394)
at java.util.Formatter$FormatSpecifierParser.parseArgumentIndexAndFlags(Formatter.java:2365)
at java.util.Formatter$FormatSpecifierParser.parseFormatToken(Formatter.java:2298)
at java.util.Formatter.doFormat(Formatter.java:1071)
at java.util.Formatter.format(Formatter.java:1042)
at java.util.Formatter.format(Formatter.java:1011)
at java.lang.String.format(String.java:1803)
at java.lang.String.format(String.java:1777)
at fr.free.nrw.commons.upload.UploadService.uploadContribution(UploadService.java:186)
at fr.free.nrw.commons.upload.UploadService.handle(UploadService.java:114)
at fr.free.nrw.commons.upload.UploadService.handle(UploadService.java:27)
at fr.free.nrw.commons.HandlerService$ServiceHandler.handleMessage(HandlerService.java:19)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.os.HandlerThread.run(HandlerThread.java:61)
```

It seems that one of the strings at https://github.com/nicolas-raoul/apps-android-commons/blob/master/commons/res/values-pl/strings.xml does not respect the syntax for parameters (maybe one of the `1$` ones).

Would you mind switching your phone to English and checking whether the crash still happen?
Then tell me and switch back to Polish so that we can fix the problem together.

**Comment by Halibutt** [comment]
Ok, switching to English solved this problem, I could take a picture now, fill in all the fields and even pick two categories. The upload still failed for some reason though and when I clicked the failed upload pic, the app crashed (I mailed the report). Awaiting further instructions. :)

**Comment by nicolas-raoul** [comment]
Could you please copy/paste the email that you sent (containing
NullPointerException) and create a new Github issue
 containing it?
Thanks a lot!

**Comment by misaochan** [comment]
@nicolas-raoul did you manage to fix this?

**Comment by nicolas-raoul** [comment]
not yet X-/

**Comment by nicolas-raoul** [comment]
@misaochan Fixed by aa3fb6e854dfabdc5d84a96c8c7561167d6d4bda
Would you mind releasing with that? Then close the issue and ask Halibutt to try.
Thanks! :-)

**Comment by misaochan** [comment]
v1.11 with fix pushed to Google Play. @Halibutt could you please test this out and let us know if it fixes the problem? Thanks. :)

**Comment by nicolas-raoul** [comment]
Not solved it seems :-/
```
USER_COMMENT=Tried to upload a pic...
ANDROID_VERSION=5.0.1
APP_VERSION_NAME=1.11
BRAND=Huawei
PHONE_MODEL=ALE-L21
CUSTOM_DATA=
STACK_TRACE=java.util.UnknownFormatConversionException: Conversion: 1$
at java.util.Formatter$FormatSpecifierParser.unknownFormatConversionException(Formatter.java:2321)
at java.util.Formatter$FormatSpecifierParser.advance(Formatter.java:2315)
at java.util.Formatter$FormatSpecifierParser.parseConversionType(Formatter.java:2394)
at java.util.Formatter$FormatSpecifierParser.parseArgumentIndexAndFlags(Formatter.java:2365)
at java.util.Formatter$FormatSpecifierParser.parseFormatToken(Formatter.java:2298)
at java.util.Formatter.doFormat(Formatter.java:1071)
at java.util.Formatter.format(Formatter.java:1042)
at java.util.Formatter.format(Formatter.java:1011)
at java.lang.String.format(String.java:1803)
at java.lang.String.format(String.java:1777)
at fr.free.nrw.commons.upload.UploadService.uploadContribution(UploadService.java:186)
at fr.free.nrw.commons.upload.UploadService.handle(UploadService.java:114)
at fr.free.nrw.commons.upload.UploadService.handle(UploadService.java:27)
at fr.free.nrw.commons.HandlerService$ServiceHandler.handleMessage(HandlerService.java:19)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by nicolas-raoul** [comment]
Fixed by f4b76fcf11291d1457b75dce6240bfcbe2f6584c hopefully, should be included in version 1.12

**Comment by Halibutt** [comment]
Just a small clarification, I uninstalled the app, reinstalled it, and started anew. Initial scraping still stops at 500 files from Commons, and the app still crashes when I try to upload a file, be it newly-made or one from my phone. Fingers crossed though :)

**Comment by misaochan** [comment]
@nicolas-raoul do we want to release 1.12 now? Or later?

**Comment by nicolas-raoul** [comment]
@misaochan Now if you have time :-)

**Comment by misaochan** [comment]
Done! Hope it works this time @Halibutt . :)

**Comment by Halibutt** [comment]
It worked! https://commons.wikimedia.org/wiki/File:BMW_door_panel.jpg

It crashed immediately afterwards, but the file is there :)

pt., 19 lut 2016, 06:35 Josephine Lim użytkownik <notifications@github.com>
napisał:

**Comment by domdomegg** [comment]
Hey @Halibutt, this is late but want to clear up some of these bugs :)

I've just cleaned up #42, and for this bug I was wondering is it the same error message you see when it crashes after you upload?

Thanks ;)

**Comment by misaochan** [comment]
Think this bug has been fixed? @Halibutt are you still experiencing issues?

**Comment by Halibutt** [comment]
Yeah, sorry I didn't answer before, all seems fine now, thank you.

**Comment by misaochan** [comment]
Awesome, thanks @Halibutt and @domdomegg  :)
